### PR TITLE
(#8) Error in vmfloaty version checking

### PR DESCRIPTION
**Pull request by dmcpl**
From this issue: https://github.com/johnmccabe/vmpooler-bitbar/issues/8

### CODE REVIEW

**Comment by johnmccabe** [comment]
oh-ho,thanks @dmcpl I'll have a look at this asap 👍

**Comment by Magisus** [comment]
I just ran into this too, and verified that the proposed patch fixes the issue. Vmfloaty updated their version API in this commit https://github.com/briancain/vmfloaty/commit/5c794cd2b0962d2716f6e5892e6cf1c3235b1bb9#diff-eb6c08d96b2757b5eef4f7fcb3a602f4.

**Comment by willmeek** [comment]
+1 on this fix, ran into this issue after my Mac updated, this allows for the version check again.

Otherwise an error occurs:

`vmpooler-bitbar.30s.rb:23:in `run': uninitialized constant VmpoolerBitbar::Version (NameError)
	from ./vmpooler-bitbar.30s.rb:360:in `<main>'`

**Comment by johnmccabe** [comment]
Thanks for the PR @dmcpl, and thanks @Magisus / @willmeek for testing. I've gone ahead and merged.

**Comment by willmeek** [comment]
Thanks @johnmccabe

**Pull request merged**
